# Generated by Django 4.1.5 on 2023-05-31 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Marka')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Renk')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Ürün Başlık')),
                ('text', models.TextField(verbose_name='Açıklama')),
                ('stok', models.IntegerField(verbose_name='Stok')),
                ('piece', models.IntegerField(verbose_name='Adet')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('rating_total', models.FloatField(verbose_name='Puanlama')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.category', verbose_name='Kategori')),
                ('colors', models.ManyToManyField(to='appShop.color', verbose_name='Renkler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Satıcı')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Yorum Başlık')),
                ('text', models.TextField(verbose_name='Yorum')),
                ('rating', models.IntegerField(verbose_name='Puan')),
                ('date_now', models.DateTimeField(auto_now_add=True, verbose_name='Tarih - Saat')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
