# Generated by Django 4.1.5 on 2023-05-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0003_remove_product_piece_alter_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
