# Generated by Django 4.1.5 on 2023-05-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='idslug',
            field=models.IntegerField(default=1, verbose_name='slugid'),
        ),
    ]
