# Generated by Django 4.1.5 on 2023-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0007_product_idslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='idslug',
        ),
    ]
