# Generated by Django 4.1.5 on 2023-05-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0008_remove_product_idslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='slug'),
        ),
    ]
