# Generated by Django 4.1.5 on 2023-05-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='text',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
