# Generated by Django 4.1.5 on 2023-06-02 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0010_alter_product_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stok',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productimg', verbose_name='Ürün Resmi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.color', verbose_name='Renk')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.product', verbose_name='Ürün')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.IntegerField(verbose_name='Stok')),
                ('price', models.FloatField(verbose_name='Fiyat')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.color', verbose_name='Renk')),
                ('images', models.ManyToManyField(to='appShop.productimage', verbose_name='Resimler')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appShop.product', verbose_name='Ürün')),
            ],
        ),
    ]
