# Generated by Django 4.1.5 on 2023-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0011_remove_product_stok_productimage_productdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product-image', verbose_name='Ürün Resmi'),
        ),
    ]
