# Generated by Django 4.1.5 on 2023-06-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title2',
            field=models.CharField(max_length=50, null=True, verbose_name='Renk İngilizce'),
        ),
    ]
